from environs import env

DEBUG = False
ENV = 'production'

SECRET_KEY = env.str('SECRET_KEY')
SECRET_KEY_FALLBACKS = env.list('SECRET_KEY_FALLBACKS', default=[])

SERVER_NAME = env.str('SERVER_NAME', default=None)
TRUSTED_HOSTS = env.list('TRUSTED_HOSTS', default=[])

MAX_CONTENT_LENGTH = env.int('MAX_CONTENT_LENGTH', default=16 * 1024 * 1024)  # 16MB

SQLALCHEMY_DATABASE_URI = env.str('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_ECHO = False
SQLALCHEMY_RECORD_QUERIES = False
SQLALCHEMY_TRACK_MODIFICATIONS = False

SESSION_COOKIE_SECURE = True
REMEMBER_COOKIE_SECURE = True
PREFERRED_URL_SCHEME = 'https'

LOG_LEVEL = 'WARNING'
